#version 460 core

layout (local_size_x = 4, local_size_y = 2, local_size_z = 4) in;

layout(binding = 0, rgba8) uniform writeonly image3D voxelsOut;

layout (std140, binding = 2) uniform voxelSettings {
    float voxelGridSize;
    float voxelRes;
};

layout (std430, binding = 1) buffer voxelIn {
    uint[] voxels;
};

vec4 uintToVec4(uint x) {
    float r = float((x >> uint(24)) & uint(0x000000FF)) / 255.0;
    float g = float((x >> uint(16)) & uint(0x000000FF)) / 255.0;
    float b = float((x >> uint(8)) & uint(0x000000FF)) / 255.0;
    float a = float((x >> uint(0)) & uint(0x000000FF)) / 255.0;
    return vec4(r, g, b, a);
}

uint vec4ToUint(vec4 x) {
    uvec4 uintVec = uvec4(floor(x * 255.0));
    return uint(
        ((uintVec.r << uint(24)) & uint(0xFF000000)) | 
        ((uintVec.g << uint(16)) & uint(0x00FF0000)) | 
        ((uintVec.b << uint(8)) & uint(0x0000FF00)) | 
        ((uintVec.a << uint(0)) & uint(0x000000FF)));
}

vec3 uintToVec3(uint x) {
    float r = float((x >> uint(21)) & uint(0x000007FF)) / 2048.0;
    float g = float((x >> uint(10)) & uint(0x000007FF)) / 2048.0;
    float b = float((x >> uint(0)) & uint(0x000003FF)) / 1024.0;
    return vec3(r, g, b);
}

uint vec3ToUint(vec3 x) {
    uvec3 uintVec = uvec3(floor(x.x * 2048.0), floor(x.y * 2048.0), floor(x.z * 1024.0));
    return uint(
        ((uintVec.r << uint(21)) & uint(0xFFE00000)) | 
        ((uintVec.g << uint(10)) & uint(0x001FFC00)) | 
        ((uintVec.b << uint(0)) & uint(0x000003FF)));
}

void main() {
    ivec3 voxelCoord = ivec3(gl_GlobalInvocationID.xyz);

    uint voxelCoord1D = uint(voxelCoord.x) + uint(voxelCoord.y) * uint(voxelRes) + uint(voxelCoord.z) * uint(voxelRes) * uint(voxelRes);
    voxelCoord1D *= 2;

    imageStore(voxelsOut, voxelCoord, vec4(uintToVec4(voxels[voxelCoord1D])));
}